spring.application.name=store_front
spring.datasource.url=jdbc:mysql://172.27.208.1:3306/pizza_planet
spring.datasource.username=pizza_user
spring.datasource.password=test
logging.level.org.springframework.security=DEBUG